/** Shared layout styles for My Library (tabs + collection detail). */
export const myLibraryStyles = {
  shell: {
    display: 'flex',
    minHeight: 'calc(100vh - var(--header-height))',
    background: '#ffffff',
    fontFamily: 'var(--font-sans)',
  },
  sidebar: {
    display: 'flex', flexDirection: 'column',
    borderRight: '1px solid #e5e7eb',
    padding: '16px 8px 8px',
    background: '#FFFFFF',
    flexShrink: 0,
    transition: 'width 150ms',
  },
  sideTab: {
    display: 'flex', flexDirection: 'column',
    alignItems: 'center', justifyContent: 'center',
    gap: '6px', padding: '14px 6px',
    border: 'none', cursor: 'pointer',
    borderRadius: '8px', marginBottom: '6px',
    fontSize: '0.7rem', fontWeight: 500,
    fontFamily: 'var(--font-sans)',
    background: 'transparent', color: '#1d4ed8',
    width: '100%',
  },
  sideLabel: { textAlign: 'center', lineHeight: 1.2 },
  collapseBtn: {
    background: '#0f172a', color: '#fff',
    width: '28px', height: '28px', borderRadius: '50%',
    border: 'none', cursor: 'pointer',
    alignSelf: 'center', marginTop: '6px',
    fontSize: '0.85rem', lineHeight: 1,
  },
  main: {
    flex: 1, padding: '32px 36px',
    display: 'flex', flexDirection: 'column',
  },
  header: {
    display: 'flex', alignItems: 'center', gap: '14px',
    marginBottom: '24px',
  },
  headerTitle: {
    fontSize: '1.4rem', fontWeight: 600,
    color: '#1d4ed8', margin: 0, letterSpacing: '-0.01em',
  },
  body: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
  },
  createBtn: {
    background: '#1d4ed8', color: '#fff', border: 'none',
    padding: '8px 16px', borderRadius: '4px',
    cursor: 'pointer', fontSize: '0.85rem', fontWeight: 600,
    display: 'inline-flex', alignItems: 'center', gap: '6px',
  },
  linkBtn: {
    background: 'transparent', border: 'none',
    color: '#6b7280', cursor: 'pointer', fontSize: '0.8rem',
    padding: '6px 8px', textDecoration: 'underline',
  },
  empty: {
    color: '#94a3b8', fontSize: '0.95rem',
    textAlign: 'center',
    margin: 'auto',
    paddingBottom: '40px',
  },
  list: { listStyle: 'none', padding: 0, margin: 0 },
  row: {
    display: 'flex', alignItems: 'center', gap: '12px',
    padding: '14px 14px',
    border: '1px solid #e5e7eb', borderRadius: '8px',
    marginBottom: '10px', background: '#fff',
  },
  rowMain: { flex: 1, color: '#0f172a', textDecoration: 'none', display: 'block' },
  rowTitle: { fontSize: '0.95rem', fontWeight: 600, color: '#0f172a' },
  rowSub: { fontSize: '0.78rem', color: '#6b7280', marginTop: '4px' },
  removeBtn: {
    background: 'transparent', border: 'none',
    color: '#94a3b8', fontSize: '1.4rem', cursor: 'pointer',
    width: '28px', height: '28px', borderRadius: '4px',
  },

  collectionsToolbar: {
    display: 'flex', justifyContent: 'flex-end', alignItems: 'center',
    gap: '24px', marginBottom: '14px',
  },
  orderBy: {
    display: 'inline-flex', alignItems: 'center', gap: '12px',
    fontSize: '0.85rem', color: '#475569',
  },
  orderLabel: { color: '#475569' },
  orderBtn: {
    background: 'transparent', border: 'none',
    fontSize: '0.85rem', color: '#94a3b8',
    cursor: 'pointer', padding: '2px 4px',
    fontFamily: 'var(--font-sans)',
  },
  orderBtnActive: {
    color: '#1d4ed8',
    textDecoration: 'underline',
    textUnderlineOffset: '2px',
  },
  filterInput: {
    width: '260px',
    padding: '8px 12px',
    border: '1px solid #cbd5e1',
    borderRadius: '4px',
    fontSize: '0.88rem',
    color: '#0f172a',
    outline: 'none',
    fontFamily: 'var(--font-sans)',
  },
  collectionsList: {
    listStyle: 'none', padding: 0, margin: 0,
    border: '1px solid #e5e7eb',
    borderRadius: '6px',
    background: '#fff',
    overflow: 'hidden',
  },
  collectionRow: {
    display: 'flex', alignItems: 'flex-start', gap: '12px',
    padding: '14px 18px',
    borderBottom: '1px solid #f1f5f9',
  },
  collectionMain: { flex: 1 },
  collectionHead: {
    display: 'inline-flex', alignItems: 'center', gap: '10px',
    marginBottom: '4px',
  },
  collectionTitle: {
    fontSize: '1rem', fontWeight: 600,
    color: '#1d4ed8', textDecoration: 'none',
  },
  collectionDesc: {
    fontSize: '0.85rem', color: '#1f2937',
    marginBottom: '4px',
  },
  collectionMeta: {
    fontSize: '0.78rem', color: '#94a3b8',
  },
  collectionActions: {
    display: 'inline-flex', alignItems: 'center', gap: '6px',
    flexShrink: 0,
  },
  iconBtn: {
    background: 'transparent', border: 'none',
    color: '#1d4ed8', cursor: 'pointer',
    padding: '6px', borderRadius: '4px',
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
  },
  pager: {
    display: 'flex', justifyContent: 'center', gap: '4px',
    marginTop: '18px',
  },
  pagerBtn: {
    background: 'transparent', border: 'none',
    color: '#1d4ed8', cursor: 'pointer',
    padding: '4px 10px', fontSize: '0.92rem',
    fontFamily: 'var(--font-sans)',
    borderRadius: '4px',
  },
  pagerBtnActive: {
    color: '#0f172a', fontWeight: 700,
    pointerEvents: 'none',
  },

  backdrop: {
    position: 'fixed', inset: 0, zIndex: 50,
    background: 'rgba(15, 23, 42, 0.45)',
    display: 'flex', justifyContent: 'flex-end',
  },
  panel: {
    width: '100%', maxWidth: '760px',
    background: '#ffffff',
    display: 'flex', flexDirection: 'column',
    boxShadow: '-12px 0 30px rgba(0,0,0,0.15)',
  },
  panelHeader: {
    display: 'flex', alignItems: 'center', gap: '14px',
    padding: '14px 18px',
    borderBottom: '1px solid #e5e7eb',
    background: '#FFFFFF',
  },
  panelClose: {
    background: 'transparent', border: 'none',
    fontSize: '1.4rem', lineHeight: 1, cursor: 'pointer',
    color: '#374151', width: '28px', height: '28px',
  },
  panelTitle: { fontSize: '0.95rem', fontWeight: 600, color: '#0f172a' },
  panelBody: { padding: '24px 28px', flex: 1 },
  fieldLabel: { display: 'block', fontSize: '0.85rem', fontWeight: 600, color: '#0f172a', marginBottom: '8px' },
  input: {
    width: '100%', padding: '10px 12px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#2563eb',
    borderRadius: '4px',
    fontSize: '0.9rem', fontFamily: 'var(--font-sans)',
    color: '#0f172a', outline: 'none', boxSizing: 'border-box',
  },
  panelActions: {
    display: 'flex', justifyContent: 'flex-end', gap: '12px',
    marginTop: '40px',
  },
  cancelBtn: {
    background: '#fff', color: '#374151',
    border: '1px solid #d1d5db', borderRadius: '4px',
    padding: '8px 18px', cursor: 'pointer',
    fontSize: '0.85rem', fontWeight: 500,
  },
  saveBtn: {
    background: '#1d4ed8', color: '#fff',
    border: 'none', borderRadius: '4px',
    padding: '8px 22px', cursor: 'pointer',
    fontSize: '0.85rem', fontWeight: 600,
  },
};
